import type { Clue } from '../engine/types';

// Notizbuch-Einträge in Seras Handschrift. IDs neutral.
export const CLUES: Clue[] = [
  { id: 'c01', name: 'Der Klingelzug', kind: 'beobachtung',
    note: 'Klingelzug am Kamin im Arbeitszimmer: Die Quaste hängt nur noch an ein paar Fäden. Da hat jemand gezogen, als ginge es um alles.' },
  { id: 'c02', name: 'Der Klingelkasten', kind: 'beobachtung',
    note: 'Klingelkasten in der Dienstbotenhalle. Die Glocke „Arbeitszimmer“ hängt schief, ihr Draht ist überdehnt. Die anderen hängen gerade.' },
  { id: 'c03', name: 'Die Taschenuhr', kind: 'gegenstand',
    note: 'Goldene Taschenuhr, E. A. graviert. Lag unter dem Bücherschrank neben dem Kamin. Glas gesprungen, Kette gerissen. Steht auf 2.39.' },
  { id: 'c04', name: 'Die Schläfe', kind: 'beobachtung',
    note: 'Beim Aufbahren: eine Schürfung an der linken Schläfe, bläulich. Nicht vom Sessel.' },
  { id: 'c05', name: 'Das Kamingitter', kind: 'beobachtung',
    note: 'Am Messinggitter vor dem Kamin, an der Kante: ein paar graue Haare und ein dunkler Fleck. Niemand hat hier geputzt.' },
  { id: 'c06', name: 'Die Totenflecken', kind: 'beobachtung',
    note: 'Totenflecken an Rücken und linker Seite, nicht in den Beinen. Clara sagt: Blut sinkt nach unten. Er hat stundenlang gelegen, nicht gesessen.' },
  { id: 'c07', name: 'Der Tantalus', kind: 'beobachtung',
    note: 'Abschließbarer Flaschenständer im Arbeitszimmer. Drei Plätze, eine Karaffe fehlt. Das Schloss ist offen.' },
  { id: 'c08', name: 'Die gespülten Gläser', kind: 'beobachtung',
    note: 'In der Butlerkammer, versteckt in der untersten Schublade unter dem Silbertuch: die Brandykaraffe aus dem Arbeitszimmer und zwei Gläser, gespült und in Leinen gewickelt.' },
  { id: 'c09', name: 'Mr. Hobbes’ Rücken', kind: 'beobachtung',
    note: 'Mr. Hobbes geht seit Mittwochfrüh, als hätte er einen Sack Kohlen getragen. Mrs. Pryce reibt ihm heimlich den Rücken ein.' },
  { id: 'c10', name: 'Das verkohlte Blatt', kind: 'dokument',
    note: 'Im Aschekasten unter dem Kamingitter: ein halb verbranntes Blatt, Briefkopf „…abbe & Tol…, London“. Darunter: „…erklären hiermit die Schuld des Capt. L. Av… für vollständig beglichen…“' },
  { id: 'c11', name: 'Bittermandelgeruch', kind: 'beobachtung',
    note: 'Im Arbeitszimmer riecht es nach Bittermandel. Am stärksten an der Tür zur Dunkelkammer.' },
  { id: 'c12', name: 'Das Fixierbad', kind: 'gegenstand',
    note: 'Dunkelkammer: eine braune Flasche, Stopfen daneben. Etikett: „Kal. cyanid. – Fixierbad. GIFT.“ Sie stand die ganze Nacht offen.' },
  { id: 'c13', name: 'Notizbuch: Belichtung', kind: 'dokument',
    note: 'Letzter Eintrag im Notizbuch des Herrn, 13. Nov.: „5 Min. vor Mitternacht. Deckel ab. Belichtung bis zum Morgen. Wandelt etwas auf der Treppe, wird die Platte es wissen. H. wird enttäuscht sein.“' },
  { id: 'c14', name: 'Notizbuch: Bath', kind: 'dokument',
    note: 'Notizbuch, August: „Bath. Dr. W.: Monate, nicht Jahre. – Abends bei Mrs. P. Ihr erzählt, was ich niemandem erzähle. Narr.“' },
  { id: 'c15', name: 'Notizbuch: Anweisung', kind: 'dokument',
    note: 'Notizbuch, 8. Nov.: „C & T – 1840 angewiesen. Dem Jungen nichts sagen, bis er es selbst fragt.“' },
  { id: 'c16', name: 'Die verhängte Kamera', kind: 'gegenstand',
    note: 'In der Halle steht auf einem Stativ ein Kasten mit Messingobjektiv, unter schwarzem Krepp wie die Spiegel. Das Objektiv zeigt auf die Treppe; ein Deckel sitzt darauf. Neben dem Stativ ein Talgtropfen.' },
  { id: 'c17', name: 'Talg auf der Treppe', kind: 'beobachtung',
    note: 'Auf den Stufen der Haupttreppe: Tropfen von Talg, nicht von Wachs. Talg riecht nach Hammel. Die Herrschaft brennt Wachs.' },
  { id: 'c18', name: 'Talg vor Claras Tür', kind: 'beobachtung',
    note: 'Auf der Galerie, direkt vor Miss Claras Tür: drei Talgtropfen dicht beieinander. Hier hat jemand gestanden und gewartet.' },
  { id: 'c19', name: 'Die nassen Stiefel', kind: 'beobachtung',
    note: 'Die Reitstiefel des Captains waren Mittwoch früh nass bis zum Schaft, mit roter Erde vom Rosenbeet unter der Terrasse. Tilly hat die Erde aufgehoben.' },
  { id: 'c20', name: 'Erde an der Terrassentür', kind: 'beobachtung',
    note: 'Auf dem Teppich an der Terrassentür im Arbeitszimmer: angetrocknete Gartenerde, ein halber Absatz. Größer als Hobbes’ Schuhe.' },
  { id: 'c21', name: 'Das Chloral', kind: 'gegenstand',
    note: 'Harriets Schlaftropfen, Chloralhydrat. Mrs. Pryce misst sie jeden Abend ab und schreibt es in ihr Buch.' },
  { id: 'c22', name: 'Die Karte', kind: 'dokument',
    note: 'Im Schreibtisch: „Mrs. E. Penrose – Sitzungen nach Vereinbarung – 14 Gay Street, Bath.“ Auf der Rückseite, in seiner Schrift: „Aug.“' },
  { id: 'c23', name: 'Der Arztbrief', kind: 'dokument',
    note: 'Dr. Wilkes, Bath, an Edmund Averley, August. Angina pectoris, fortgeschritten. „Ich kann Ihnen keine Jahre versprechen.“ Miss Averley hat ihn aufbewahrt.' },
  { id: 'c24', name: 'Die automatische Schrift', kind: 'dokument',
    note: 'In der Bibliothek, unter dem Séancetisch: ein Blatt in Harriets Hand, schief und fahrig: „Er kommt bald zu mir. Hab keine Angst. L.“' },
  { id: 'c25', name: 'Das Angebot', kind: 'dokument',
    note: 'Brief der Bath Royal Literary and Scientific Institution, 10. Nov.: Man biete 700 Pfund für die Sammlung des Herrn – Instrumente, Platten, Moose und Gesteine.' },
  { id: 'c26', name: 'Das Taschentuch', kind: 'gegenstand',
    note: 'Unter dem Sessel im Gästezimmer (Yuumi): ein Taschentuch, zerknüllt, Monogramm C. A. Es riecht nach Rosenwasser und ganz schwach nach Fixierbad.' },
  { id: 'c27', name: 'Mrs. Pryces Brief', kind: 'dokument',
    note: 'Ein angefangener Brief auf Mrs. Pryces Tisch: „Mein lieber Owen, Mittwoch, 2 Uhr früh, und ich kann nicht schlafen …“ Er bricht mitten im Satz ab.' },
  { id: 'c28', name: 'Tillys Kerzenstummel', kind: 'gegenstand',
    note: 'Tillys Talgkerze auf dem Küchenbord ist fast heruntergebrannt. Mrs. Pryce gibt ihr jeden Abend eine neue. Tilly war also lange auf.' },
  { id: 'c29', name: 'Die Platte', kind: 'gegenstand',
    note: 'Die entwickelte Glasplatte. Blasse Lichtspuren über Treppe und Hallenboden, ein heller Fleck oben vor einer Tür, eine breite Lampenspur, eine kurze am Morgen (Hobbes). Auf den Stufen ein Mädchen mit Kerze. Daneben, schwächer, eine Frau mit hellem Haar und ein kleines Tier.' },
  { id: 'c30', name: 'Der Brief an Clara', kind: 'dokument',
    note: 'Edmunds letzter Brief, adressiert „Für Clara. Nur für sie.“ Tilly hat ihn drei Tage in ihrer Blechdose verwahrt. Am Rand ein Fingerabdruck aus Kohle.' },
  { id: 'c31', name: 'Der Brief der Agentur', kind: 'dokument',
    note: 'Mrs. Crewes Agentur, London: Miss Sarah Hale liege mit Influenza in Bristol und bedaure, ihre Stellung nicht antreten zu können.' },
  { id: 'c32', name: 'Die angehaltenen Uhren', kind: 'beobachtung',
    note: 'Alle Uhren im Haus stehen auf 6.25. So hält man es hier, wenn jemand stirbt: Man hält die Zeit an. Nur – ist das die Zeit, zu der er starb?' },
  { id: 'e01', name: 'Kerzenschein (Traum?)', kind: 'erinnerung',
    note: 'Bevor ich hier aufwachte: ein Licht, das die Treppe hinaufwanderte. Wie durch Wasser.' },
  { id: 'e02', name: 'Klopfen (Traum?)', kind: 'erinnerung',
    note: 'Ein Klopfen, oben, leise und lange. Eine Kinderstimme: „Bitte, machen Sie auf.“' },
  { id: 'e03', name: 'Läuten (Traum?)', kind: 'erinnerung',
    note: 'Weit unten, tief im Haus, hat eine Glocke geläutet. Einmal. Hart.' },
  { id: 'e04', name: 'Flüstern (Traum?)', kind: 'erinnerung',
    note: '„… wenn mich doch nur einer …“ – aus dem Glas. Oder aus mir.' },
];

export const CLUE_BY_ID = Object.fromEntries(CLUES.map((c) => [c.id, c]));
