import type { Deduction } from '../engine/types';

// Schlussfolgerungen. Die Spielerin füllt Lücken; angenommen wird nur mit ≥ need Stützen.
export const DEDUCTIONS: Deduction[] = [
  {
    id: 'd01', chapter: 1, trigger: ['c01', 'c02', 'e03'], support: ['c01', 'c02', 'e03'], need: 2,
    question: 'Wer hat in der Nacht geläutet?',
    template: 'In der Nacht wurde im {0} heftig nach Hilfe geläutet.',
    slots: [{ options: ['Arbeitszimmer', 'Salon', 'Bibliothek', 'Zimmer von Miss Averley'], correct: [0] }],
    result: 'Jemand hat nachts im Arbeitszimmer geläutet. Und zwar mit aller Kraft.',
    doubt: ['Nein. Das passt nicht zu dem, was ich gesehen habe.', 'Ich rede mir da was ein. Okay, noch mal von vorn.', 'Yuumi guckt mich an. So guckt sie, wenn ich ihr das falsche Futter hinstelle.'],
    hints: ['So eine Klingel hat zwei Enden.', 'An einem Ende zieht man. Am anderen Ende klingelt es.', 'Der Kamin im Arbeitszimmer. Und der Kasten in der Dienstbotenhalle.'],
  },
  {
    id: 'd02', chapter: 1, contradiction: true, trigger: ['s02'], support: ['s02', 'd01', 'c02'], need: 2,
    question: 'Stimmt, was Mrs. Pryce sagt?',
    template: 'Mrs. Pryce sagt, es habe keine Glocke geläutet. Aber {0}.',
    slots: [{ options: ['der Draht der Glocke „Arbeitszimmer“ ist überdehnt', 'Miss Averley hat Schlaftropfen genommen', 'die Uhren stehen auf 6.25', 'Tilly hat ein Glöckchen gehört'], correct: [0] }],
    result: 'Mrs. Pryce sagt über die Glocke nicht die Wahrheit. Sie schützt jemanden. Oder sich selbst.',
    doubt: ['Das beweist nichts über die Glocke im Arbeitszimmer.', 'Nein. Das Glöckchen, das Tilly gehört hat, war ein anderes. Und ich weiß zufällig, welches.', 'Nicht das. Ich brauche etwas, das man anfassen kann.'],
    hints: ['Gegen eine Lüge brauche ich einen Beweis.', 'Wo im Haus sieht man noch, dass geläutet wurde, auch wenn es keiner zugibt?', 'Der Klingelkasten in der Dienstbotenhalle.'],
    effects: { flags: ['g_pryce_doubt'] },
  },
  {
    id: 'd03', chapter: 1, trigger: ['c03', 'c05', 'c04', 'c06'], support: ['c03', 'c05', 'c04', 'c06'], need: 2,
    question: 'Ist er im Sessel gestorben?',
    template: 'Der Herr ist nicht sanft entschlafen. Er ist {0} und lag danach {1}.',
    slots: [
      { options: ['gestürzt', 'vergiftet worden', 'im Schlaf gestorben'], correct: [0] },
      { options: ['am Boden', 'im Sessel', 'im Bett'], correct: [0] },
    ],
    result: 'Er ist gestürzt und mit dem Kopf gegen das Kamingitter geschlagen. Die Uhr ist unter den Schrank gerutscht. Er lag am Boden. Erst später hat ihn jemand in den Sessel gesetzt.',
    doubt: ['Dann würde die Uhr nicht unter dem Schrank liegen.', 'Nein. Da ist etwas gefallen. Oder jemand.', 'Ich hätte gern, dass es friedlich war. Aber das ist kein Beweis.'],
    hints: ['Was herunterfällt, landet irgendwo.', 'Wie kommt eine Uhr an einer Kette unter einen schweren Schrank? Und was ist mit dem Gitter?', 'Unter dem Bücherschrank. Und an der Kante vom Kamingitter.'],
  },
  {
    id: 'd04', chapter: 2, contradiction: true, trigger: ['s01'], support: ['s01', 'd03', 'c06', 'c09'], need: 2,
    question: 'Stimmt, was Mr. Hobbes sagt?',
    template: 'Mr. Hobbes sagt, er habe den Herrn im Sessel gefunden. Aber {0}.',
    slots: [{ options: ['die Totenflecken zeigen, dass er stundenlang lag', 'Mr. Hobbes hat die Uhren angehalten', 'der Tantalus ist offen', 'die Kamera ist verhängt'], correct: [0] }],
    result: 'Mr. Hobbes hat den Herrn am Boden gefunden und in den Sessel gesetzt. Friedlich entschlafen ist er dort nicht.',
    doubt: ['Das hat Hobbes nicht getan. Und selbst wenn, sagt es nichts über den Sessel.', 'Nein. Was sagt der Körper selbst?', 'Clara würde jetzt die Augen verdrehen. Zu Recht.'],
    hints: ['Vielleicht sagt der Tote selbst etwas anderes als Mr. Hobbes.', 'Was hat Clara beim Aufbahren gesagt?', 'Die Totenflecken. Und Hobbes’ Rücken.'],
  },
  {
    id: 'd05', chapter: 2, trigger: ['c03'], support: ['c03', 'c04', 'c05'], need: 2,
    question: 'Wann ist er gestürzt?',
    template: 'Der Herr stürzte um {0}.',
    slots: [{ options: ['2.39 Uhr', '6.25 Uhr', 'Mitternacht', '1.20 Uhr'], correct: [0] }],
    result: 'Er ist um 2.39 Uhr gestürzt. Die Uhren im Haus stehen auf 6.25. Das ist nur die Zeit, zu der Hobbes sie angehalten hat.',
    doubt: ['Die Uhren im Haus hat jemand angehalten. Die Uhr in seiner Tasche nicht.', 'Nein. Da hat man ihn gefunden. Gestürzt ist er früher.', 'Genau hinschauen, Sera. Das sage ich meinen Schülern auch immer.'],
    hints: ['Nicht jede Uhr, die steht, hat jemand angehalten.', 'Welche Uhr ist mit ihm gefallen?', 'Die Taschenuhr unter dem Bücherschrank.'],
  },
  {
    id: 'd06', chapter: 2, trigger: ['c11', 's12'], support: ['c11', 'c12', 's13'], need: 2,
    question: 'Woher kommt der Bittermandelgeruch?',
    template: 'Der Bittermandelgeruch im Arbeitszimmer kommt vom {0}.',
    slots: [{ options: ['Fixierbad der Dunkelkammer', 'Gift in seinem Glas', 'Mandelgebäck vom Dinner', 'Rauch aus dem Kamin'], correct: [0] }],
    result: 'Der Geruch kommt aus der Dunkelkammer. Fixierbad mit Kaliumcyanid, und die Flasche stand offen. Im Glas war kein Gift.',
    doubt: ['Der Captain würde mir zustimmen. Das ist kein gutes Zeichen.', 'Wo riecht es am stärksten?', 'Nein. Ich hab zu viele Krimis mit Bittermandel gelesen und zu wenig über Fotografie.'],
    hints: ['Ein Geruch kommt irgendwoher.', 'Wo ist er am stärksten? Und was steht dort?', 'Die Dunkelkammer. Und frag Clara.'],
    effects: { flags: ['g_no_poison'] },
  },
  {
    id: 'd07', chapter: 2, trigger: ['c07', 'c08'], support: ['c07', 'c08', 's15'], need: 2,
    question: 'Hat in der Nacht jemand mit ihm getrunken?',
    template: 'In der Nacht wurden {0} Gläser benutzt, und jemand hat sie {1}.',
    slots: [
      { options: ['zwei', 'ein', 'drei'], correct: [0] },
      { options: ['gespült und fortgeräumt', 'stehen lassen', 'zerschlagen'], correct: [0] },
    ],
    result: 'Er hat nachts mit jemandem Brandy getrunken. Zwei Gläser. Und jemand hat sie gespült und weggeräumt, bevor irgendwer fragen konnte.',
    doubt: ['Dann hätte er allein getrunken. Aus zwei Gläsern. Eher nicht.', 'Wer räumt in diesem Haus wann was weg?', 'Nein, die Gläser stehen ja gar nicht mehr da. Das ist doch der Punkt.'],
    hints: ['Etwas fehlt. Und etwas ist zu sauber.', 'Der Tantalus. Und wo spült man in diesem Haus Gläser?', 'Die Butlerkammer. Und frag Tilly, wann Mr. Hobbes spült.'],
  },
  {
    id: 'd08', chapter: 3, contradiction: true, trigger: ['s03'], support: ['s03', 's06', 'c19', 'c20'], need: 2,
    question: 'Hat der Captain geschlafen?',
    template: 'Der Captain sagt, er habe ab Mitternacht geschlafen. Aber {0}.',
    slots: [{ options: ['er war in der Nacht draußen im Regen, vor dem Arbeitszimmer', 'er hat bei der Séance gespottet', 'er hat Schulden', 'er riecht nach Brandy'], correct: [0] }],
    result: 'Der Captain hat nicht geschlafen. Er war nachts draußen im Regen, vor dem Arbeitszimmer.',
    doubt: ['Er spottet und trinkt, okay. Deshalb kann er trotzdem im Bett gelegen haben.', 'Ich brauche jemanden, der ihn gesehen hat. Oder seine Stiefel.', 'Nein. Ich brauche etwas Genaueres.'],
    hints: ['Wer nachts draußen war, bringt etwas mit herein.', 'Wer ist nachts draußen, wenn das Wasser steigt?', 'Dunning im Stallhof. Und die Stiefelkammer.'],
  },
  {
    id: 'd09', chapter: 3, trigger: ['c10'], support: ['c10', 's19', 'd08'], need: 2,
    question: 'Wer hat im Kamin Papier verbrannt?',
    template: 'In der Nacht hat {0} Papiere im Kamin des Arbeitszimmers verbrannt.',
    slots: [{ options: ['der Captain', 'Mr. Hobbes', 'Miss Clara', 'der Herr selbst'], correct: [0] }],
    result: 'Der Captain hat Papiere verbrannt, und zwar Papiere über seine eigenen Schulden. Er kam von der Terrasse zurück, und niemand sollte sie finden.',
    doubt: ['Hobbes hat in der Asche gestochert. Verbrannt hat er nichts. Er hat nur versteckt, was schon gebrannt hat.', 'Wer hatte einen Grund, genau diese Papiere loszuwerden?', 'Nein. Wessen Name steht auf dem Blatt?'],
    hints: ['Wessen Name steht auf dem Blatt?', 'Wer war nachts in der Nähe? Und wer hat danach auffällig saubere Hände?', 'Das verkohlte Blatt, Dunnings Beobachtung und das, was Mrs. Penrose über Hände sagt.'],
  },
  {
    id: 'd10', chapter: 3, trigger: ['c10'], support: ['c10', 'c15'], need: 2,
    question: 'Was stand auf den verbrannten Papieren?',
    template: 'Die verbrannten Papiere bewiesen, dass die Schulden des Captains {0} waren.',
    slots: [{ options: ['bereits bezahlt', 'gefälscht', 'fällig', 'vergessen'], correct: [0] }],
    result: 'Sein Vater hatte die Schulden bezahlt. 1840 Pfund, am 8. November. Und jemand hat den Beweis dafür verbrannt.',
    doubt: ['Noch mal lesen, was auf dem Blatt steht. Ganz genau.', 'Nein. Im Notizbuch steht was anderes.', 'Fritz würde jetzt sagen: Lies, was da steht, nicht was du erwartest. Er hat leider recht.'],
    hints: ['Einfach mal lesen, was auf dem Blatt steht. Wort für Wort.', '„Vollständig beglichen“. Und was steht dazu im Notizbuch?', 'Der Eintrag vom 8. November.'],
    effects: { flags: ['g_paid_known'] },
  },
  {
    id: 'd11', chapter: 3, trigger: ['c13', 'c16'], support: ['c13', 'c16', 's10'], need: 2,
    question: 'Was hat die Kamera gesehen?',
    template: 'Die Kamera in der Halle hat {0} belichtet.',
    slots: [{ options: ['die ganze Nacht', 'nur einen Augenblick', 'gar nicht'], correct: [0] }],
    result: 'Die Kamera stand die ganze Nacht offen und zeigte auf die Treppe. Die Platte steckt noch drin. Darauf müsste jeder zu sehen sein, der vorbeigegangen ist.',
    doubt: ['Er hat es doch aufgeschrieben.', 'Wo ist der Deckel?', 'Nein. Seitdem hat sie niemand angefasst.'],
    hints: ['Eine Kamera sieht, solange sie offen ist.', 'Was hat er um 23.55 geschrieben? Und hat seitdem jemand die Kamera angefasst?', 'Das Notizbuch, die Kamera selbst und Mr. Hobbes.'],
    effects: { flags: ['g_camera_known'] },
  },
  {
    id: 'd12', chapter: 3, trigger: ['c24', 'c14', 'c23', 's39'], support: ['c24', 'c14', 'c23', 's39'], need: 2,
    question: 'Was wusste Miss Averley?',
    template: 'Miss Averley wusste, dass ihr Bruder {0}.',
    slots: [{ options: ['bald sterben würde', 'ermordet werden sollte', 'das Haus verkaufen wollte'], correct: [0] }],
    result: 'Harriet wusste von seiner Krankheit. „Er kommt bald zu mir“ ist keine Drohung. Sie wusste, dass ihr Bruder bald sterben würde, und hat schon vorher um ihn getrauert.',
    doubt: ['So finster ist sie nicht. Glaube ich jedenfalls.', 'Nein. Was wusste er selbst seit August?', 'Wer ist eigentlich „L.“?'],
    hints: ['„L.“ ist nicht Lionel.', 'Was wusste der Herr seit August?', 'Das Notizbuch (Bath). Und das Blatt unter dem Séancetisch.'],
  },
  {
    id: 'd13', chapter: 4, trigger: ['c17', 'c18'], support: ['c17', 'c18', 'e02', 'c28'], need: 2,
    question: 'Wer war nachts auf der Haupttreppe?',
    template: 'In der Nacht lief {0} mit einer Talgkerze über die Haupttreppe bis vor {1} Tür.',
    slots: [
      { options: ['ein Dienstbote', 'jemand von der Familie', 'ein Gast'], correct: [0] },
      { options: ['Miss Claras', 'Miss Averleys', 'des Captains', 'Mrs. Penroses'], correct: [0] },
    ],
    result: 'Ein Dienstbote ist nachts mit einer Talgkerze die Haupttreppe hinaufgelaufen, obwohl die für Dienstboten verboten ist. Oben hat er lange vor Claras Tür gewartet.',
    doubt: ['Die Herrschaft brennt Wachs. Talg ist für die Dienstboten.', 'Wo genau lagen die Tropfen oben?', 'Nein. Das Klopfen im Traum war an einer ganz bestimmten Tür.'],
    hints: ['Nicht jeder im Haus brennt dieselben Kerzen.', 'Talg oder Wachs? Und wo oben liegen die Tropfen dicht nebeneinander?', 'Die Stufen. Und die Galerie vor den Türen.'],
  },
  {
    id: 'd14', chapter: 4, contradiction: true, trigger: ['c26'], support: ['s04', 's05', 'c26', 's36'], need: 2,
    question: 'Wo war Clara in der Nacht?',
    template: 'Clara sagt, sie sei zu Bett gegangen, Mrs. Penrose sagt, sie habe geschlafen. Aber {0}.',
    slots: [{ options: ['Claras Taschentuch lag unter dem Sessel im Gästezimmer', 'Clara hat schwarze Finger', 'Mrs. Penrose trägt Ringe', 'die Séance war um elf vorbei'], correct: [0] }],
    result: 'Clara war nachts bei Mrs. Penrose. Deshalb hat niemand aufgemacht, als es an ihrer Tür geklopft hat.',
    doubt: ['Das beweist nur, dass sie fotografiert.', 'Wer hat was in wessen Zimmer vergessen?', 'Nein. Yuumi hat mir doch was gebracht. Kluge Katze.'],
    hints: ['Wer irgendwo war, lässt manchmal etwas liegen.', 'Was hat Yuumi im Gästezimmer gefunden?', 'Das Taschentuch. Und das Licht im Gästeflügel, das Dunning gesehen hat.'],
  },
  {
    id: 'd15', chapter: 4, trigger: ['c22', 'c14', 's22'], support: ['c22', 'c14', 's22'], need: 2,
    question: 'Woher kannte das Medium die Glocke im Wasser?',
    template: 'Die Botschaft der Séance stammte {0}.',
    slots: [{ options: ['vom Herrn selbst, aus Bath', 'von Miss Averley', 'aus dem Jenseits', 'aus dem Dienstbotenklatsch'], correct: [0] }],
    result: 'Er hat es ihr selbst erzählt, im August in Bath, ohne seinen Namen zu nennen. Bei der Séance hat er seine eigenen Worte gehört und verstanden, dass sie von ihm kamen.',
    doubt: ['Miss Averley kannte Lucindas Wunsch. Aber die Worte am Sterbebett hat sie nicht gehört, sagt sie. Die kannte nur er.', 'Nein. Wer war im August in Bath?', 'Geister? Ach nee. Ich glaube eher an Karten in Schreibtischen.'],
    hints: ['Wer war im August wo?', 'Die Karte in seinem Schreibtisch. Und sein eigener Eintrag über Bath.', 'Schreibtisch, Notizbuch. Und frag Mrs. Penrose, mit der Karte in der Hand.'],
  },
  {
    id: 'd16', chapter: 4, trigger: ['c29'], support: ['c29', 'c28', 'd13'], need: 2,
    question: 'Wer ist das Mädchen auf der Platte?',
    template: 'Das Mädchen, das auf der Platte mit einer Kerze auf der Treppe sitzt, ist {0}.',
    slots: [{ options: ['Tilly', 'Clara', 'eine Erscheinung', 'Mrs. Penrose'], correct: [0] }],
    result: 'Es ist Tilly. Sie saß nachts auf der Haupttreppe, lange genug, dass sie auf der Platte zu sehen ist.',
    doubt: ['Clara nimmt Wachskerzen. Und eine Haube hätte sie auch nicht auf.', 'Ich will jetzt nicht an Gespenster glauben. Echt nicht.', 'Nein. Wessen Kerze war heruntergebrannt?'],
    hints: ['Das Mädchen trägt eine Haube und hat eine Talgkerze.', 'Wer im Haus hatte am Morgen eine fast heruntergebrannte Kerze?', 'Tillys Kerzenstummel in der Küche.'],
    effects: { flags: ['g_girl_known'] },
  },
  {
    id: 'd17', chapter: 4, trigger: ['d02', 'c27'], support: ['d02', 'c27', 'c28'], need: 2,
    question: 'Wen hat die Glocke gerufen?',
    template: 'Die Glocke um halb drei rief {0}, und {1} blieb sitzen.',
    slots: [
      { options: ['Tilly', 'Mr. Hobbes', 'Mrs. Pryce'], correct: [0] },
      { options: ['Mrs. Pryce', 'Mr. Hobbes', 'Tilly'], correct: [0] },
    ],
    result: 'Mrs. Pryce war wach. Sie hat die Glocke gehört und Tilly gehen lassen. Sie selbst ist sitzen geblieben. Deshalb lügt sie.',
    doubt: ['Hobbes schläft wie ein Stein, das sagen alle.', 'Wer war um zwei Uhr wach und hat es aufgeschrieben?', 'Nein. Wer hat sich danach schuldig benommen?'],
    hints: ['Wer war wach?', 'Ein Brief, um zwei Uhr früh angefangen und nie zu Ende geschrieben.', 'Mrs. Pryces Tisch. Und Tillys Kerze.'],
  },
  {
    id: 'd18', chapter: 5, trigger: ['c30'], support: ['c25', 'c30', 's11', 'd10'], need: 2,
    question: 'Was wollte er in seiner letzten Nacht?',
    template: 'In seiner letzten Nacht wollte der Herr {0}.',
    slots: [{ options: ['Clara den Weg öffnen und Lionel freisprechen', 'Lionel enterben', 'Lucinda rufen', 'das Haus verkaufen'], correct: [0] }],
    result: 'Er wollte alles in Ordnung bringen, bevor er starb. Lionels Schulden waren bezahlt, und Clara sollte die Sammlung verkaufen und studieren. Er hat es nur niemandem rechtzeitig gesagt.',
    doubt: ['Das hat der Captain befürchtet. Deshalb muss es noch lange nicht stimmen.', 'Nein. Was stand in dem Angebot aus Bath?', 'Ich lese den Brief lieber noch mal.'],
    hints: ['Was sollte am Morgen unterschrieben werden?', 'Das Angebot der Institution, der Brief und die Quittung.', 'Alles, was auf seinem Schreibtisch lag.'],
    effects: { flags: ['g_will_known'] },
  },
];

export const DEDUCTION_BY_ID = Object.fromEntries(DEDUCTIONS.map((d) => [d.id, d]));
