import type { Deduction } from '../engine/types';

// Schlussfolgerungen. Die Spielerin füllt Lücken; angenommen wird nur mit ≥ need Stützen.
export const DEDUCTIONS: Deduction[] = [
  {
    id: 'd01', chapter: 1, trigger: ['c01', 'c02', 'e03'], support: ['c01', 'c02', 'e03'], need: 2,
    question: 'Wer hat in der Nacht geläutet?',
    template: 'In der Nacht wurde im {0} heftig nach Hilfe geläutet.',
    slots: [{ options: ['Arbeitszimmer', 'Salon', 'Bibliothek', 'Zimmer von Miss Averley'], correct: [0] }],
    result: 'Jemand hat nachts im Arbeitszimmer geläutet – mit aller Kraft.',
    doubt: ['Nein. Das passt nicht zu dem, was ich gesehen habe.', 'Ich rede mir etwas ein. Noch einmal von vorn.', 'Yuumi würde mich jetzt ansehen, als hätte ich den Futternapf verwechselt.'],
    hints: ['Eine Glocke hat zwei Enden.', 'Das eine Ende hängt dort, wo man zieht. Das andere dort, wo es klingelt.', 'Der Kamin im Arbeitszimmer – und der Kasten in der Dienstbotenhalle.'],
  },
  {
    id: 'd02', chapter: 1, contradiction: true, trigger: ['s02'], support: ['s02', 'd01', 'c02'], need: 2,
    question: 'Stimmt, was Mrs. Pryce sagt?',
    template: 'Mrs. Pryce sagt, es habe keine Glocke geläutet. Aber {0}.',
    slots: [{ options: ['der Draht der Glocke „Arbeitszimmer“ ist überdehnt', 'Miss Averley hat Schlaftropfen genommen', 'die Uhren stehen auf 6.25', 'Tilly hat ein Glöckchen gehört'], correct: [0] }],
    result: 'Mrs. Pryce sagt nicht die Wahrheit über die Glocke. Sie schützt jemanden. Oder sich.',
    doubt: ['Das beweist nichts über die Glocke im Arbeitszimmer.', 'Nein – das Glöckchen, das Tilly hörte, war ein anderes. Ich weiß zufällig, welches.', 'Nicht das. Etwas, das man anfassen kann.'],
    hints: ['Eine Lüge braucht einen Gegenbeweis.', 'Was im Haus erinnert sich an ein Läuten, auch wenn Menschen es vergessen wollen?', 'Der Klingelkasten in der Dienstbotenhalle.'],
    effects: { flags: ['g_pryce_doubt'] },
  },
  {
    id: 'd03', chapter: 1, trigger: ['c03', 'c05', 'c04', 'c06'], support: ['c03', 'c05', 'c04', 'c06'], need: 2,
    question: 'Ist er im Sessel gestorben?',
    template: 'Der Herr ist nicht sanft entschlafen. Er ist {0} und lag danach {1}.',
    slots: [
      { options: ['gestürzt', 'vergiftet worden', 'im Schlaf gestorben'], correct: [0] },
      { options: ['am Boden', 'im Sessel', 'im Bett'], correct: [0] },
    ],
    result: 'Er ist gestürzt – mit dem Kopf gegen das Kamingitter, die Uhr flog unter den Schrank. Er lag am Boden. Jemand hat ihn später in den Sessel gesetzt.',
    doubt: ['Dann würde die Uhr nicht unter dem Schrank liegen.', 'Nein. Irgendetwas ist gefallen. Irgendwer.', 'Ich will, dass es friedlich war. Das ist kein Beweis.'],
    hints: ['Dinge, die fallen, landen irgendwo.', 'Wie kommt eine Uhr an der Kette unter einen schweren Schrank? Und was ist mit dem Gitter?', 'Unter dem Bücherschrank und an der Kante des Kamingitters.'],
  },
  {
    id: 'd04', chapter: 2, contradiction: true, trigger: ['s01'], support: ['s01', 'd03', 'c06', 'c09'], need: 2,
    question: 'Stimmt, was Mr. Hobbes sagt?',
    template: 'Mr. Hobbes sagt, er habe den Herrn im Sessel gefunden. Aber {0}.',
    slots: [{ options: ['die Totenflecken zeigen, dass er stundenlang lag', 'Mr. Hobbes hat die Uhren angehalten', 'der Tantalus ist offen', 'die Kamera ist verhängt'], correct: [0] }],
    result: 'Mr. Hobbes hat den Herrn am Boden gefunden und in den Sessel gesetzt. Deshalb sein Rücken.',
    doubt: ['Das hat Hobbes nicht getan, oder wenn doch, beweist es nichts über den Sessel.', 'Nein. Was sagt der Körper selbst?', 'Clara würde jetzt die Augen verdrehen. Zu Recht.'],
    hints: ['Ein Körper lügt nicht aus Pietät.', 'Was hat Clara beim Aufbahren gesagt?', 'Die Totenflecken – und Hobbes’ Rücken.'],
  },
  {
    id: 'd05', chapter: 2, trigger: ['c03'], support: ['c03', 'c04', 'c05'], need: 2,
    question: 'Wann ist er gestürzt?',
    template: 'Der Herr stürzte um {0}.',
    slots: [{ options: ['2.39 Uhr', '6.25 Uhr', 'Mitternacht', '1.20 Uhr'], correct: [0] }],
    result: 'Er stürzte um 2.39 Uhr. Die Uhren im Haus stehen auf 6.25 – das ist nur die Zeit, zu der Hobbes sie anhielt.',
    doubt: ['Die Uhren im Haus hat jemand angehalten. Die Uhr in seiner Tasche nicht.', 'Nein, das ist die Zeit, zu der man ihn fand, nicht die, zu der er fiel.', 'Ich muss genauer lesen.'],
    hints: ['Nicht jede stehengebliebene Uhr wurde angehalten.', 'Welche Uhr ist mit ihm gefallen?', 'Die Taschenuhr unter dem Bücherschrank.'],
  },
  {
    id: 'd06', chapter: 2, trigger: ['c11', 's12'], support: ['c11', 'c12', 's13'], need: 2,
    question: 'Woher kommt der Bittermandelgeruch?',
    template: 'Der Bittermandelgeruch im Arbeitszimmer kommt vom {0}.',
    slots: [{ options: ['Fixierbad der Dunkelkammer', 'Gift in seinem Glas', 'Mandelgebäck vom Dinner', 'Rauch aus dem Kamin'], correct: [0] }],
    result: 'Der Geruch kommt aus der Dunkelkammer: Fixierbad mit Kaliumcyanid, die Flasche stand offen. Kein Gift im Glas.',
    doubt: ['Der Captain würde mir zustimmen. Das ist kein gutes Zeichen.', 'Wo ist der Geruch am stärksten?', 'Nein. Ich habe in Krimis zu viel über Bittermandel gelernt und zu wenig über Fotografie.'],
    hints: ['Gerüche haben eine Quelle.', 'Wo ist er am stärksten – und was steht dort?', 'Die Dunkelkammer, und frag Clara.'],
    effects: { flags: ['g_no_poison'] },
  },
  {
    id: 'd07', chapter: 2, trigger: ['c07', 'c08'], support: ['c07', 'c08', 's15'], need: 2,
    question: 'Hat in der Nacht jemand mit ihm getrunken?',
    template: 'In der Nacht wurden {0} Gläser benutzt, und jemand hat sie {1}.',
    slots: [
      { options: ['zwei', 'ein', 'drei'], correct: [0] },
      { options: ['vor dem Frühstück gespült', 'stehen lassen', 'zerschlagen'], correct: [0] },
    ],
    result: 'Er hat nachts mit jemandem Brandy getrunken. Zwei Gläser. Und jemand hat sie vor dem Frühstück gespült und versteckt – gegen jede Gewohnheit im Haus.',
    doubt: ['Das hieße, er trank allein. Aus zwei Gläsern.', 'Wer räumt in diesem Haus was wann weg?', 'Nein, die Gläser stehen nicht mehr da. Das ist ja der Punkt.'],
    hints: ['Etwas fehlt, und etwas ist zu sauber.', 'Der Tantalus – und wo man in diesem Haus Gläser spült.', 'Die Butlerkammer. Und frag Tilly, wann Mr. Hobbes spült.'],
  },
  {
    id: 'd08', chapter: 3, contradiction: true, trigger: ['s03'], support: ['s03', 's06', 'c19', 'c20'], need: 2,
    question: 'Hat der Captain geschlafen?',
    template: 'Der Captain sagt, er habe ab Mitternacht geschlafen. Aber {0}.',
    slots: [{ options: ['Dunning sah ihn kurz vor drei auf der Terrasse', 'er hat bei der Séance gespottet', 'er hat Schulden', 'er riecht nach Brandy'], correct: [0] }],
    result: 'Der Captain war nachts draußen auf der Terrasse, vor dem Arbeitszimmer. Seine Stiefel und die Erde an der Terrassentür sagen dasselbe wie Dunning.',
    doubt: ['Dass er spottet oder trinkt, heißt nicht, dass er nicht im Bett lag.', 'Ich brauche jemanden, der ihn gesehen hat. Oder seine Stiefel.', 'Nein. Etwas Genaueres.'],
    hints: ['Wer nachts draußen war, bringt etwas mit herein.', 'Wer im Haus ist nachts draußen unterwegs, wenn das Wasser steigt?', 'Dunning im Stallhof – und die Stiefelkammer.'],
  },
  {
    id: 'd09', chapter: 3, trigger: ['c10'], support: ['c10', 's19', 'd08'], need: 2,
    question: 'Wer hat im Kamin Papier verbrannt?',
    template: 'In der Nacht hat {0} Papiere im Kamin des Arbeitszimmers verbrannt.',
    slots: [{ options: ['der Captain', 'Mr. Hobbes', 'Miss Clara', 'der Herr selbst'], correct: [0] }],
    result: 'Der Captain hat Papiere verbrannt – seine eigenen Schuldsachen. Er kam von der Terrasse zurück, und niemand sollte sie finden.',
    doubt: ['Hobbes hat in der Asche gestochert. Verbrannt hat er nicht – er hat versteckt, was schon brannte.', 'Wer hatte einen Grund, genau diese Papiere loszuwerden?', 'Nein. Wessen Name steht auf dem Blatt?'],
    hints: ['Wessen Name steht auf dem Blatt?', 'Wer war nachts in der Nähe, und wer hat danach auffällig saubere Hände?', 'Das Aschefragment, Dunnings Beobachtung, und was Mrs. Penrose über Hände sagt.'],
  },
  {
    id: 'd10', chapter: 3, trigger: ['c10'], support: ['c10', 'c15'], need: 2,
    question: 'Was stand auf den verbrannten Papieren?',
    template: 'Die verbrannten Papiere bewiesen, dass die Schulden des Captains {0} waren.',
    slots: [{ options: ['bereits bezahlt', 'gefälscht', 'fällig', 'vergessen'], correct: [0] }],
    result: 'Sein Vater hatte die Schulden bezahlt – 1840 Pfund, am 8. November. Und jemand hat den Beweis dafür verbrannt.',
    doubt: ['Lies noch einmal, was auf dem Blatt steht. Genau.', 'Nein. Das Notizbuch sagt etwas anderes.', 'Ich sehe, was ich erwarte. Nicht, was dasteht.'],
    hints: ['Lies das Blatt wie einen Brief, nicht wie ein Beweisstück.', '„Vollständig beglichen“ – und was steht dazu im Notizbuch?', 'Der Eintrag vom 8. November.'],
    effects: { flags: ['g_paid_known'] },
  },
  {
    id: 'd11', chapter: 3, trigger: ['c13', 'c16'], support: ['c13', 'c16', 's10'], need: 2,
    question: 'Was hat die Kamera gesehen?',
    template: 'Die Kamera in der Halle hat {0} belichtet.',
    slots: [{ options: ['die ganze Nacht', 'nur einen Augenblick', 'gar nicht'], correct: [0] }],
    result: 'Die Kamera stand die ganze Nacht offen auf die Treppe gerichtet. Die Platte steckt noch darin. Sie hat gesehen, wer vorbeiging.',
    doubt: ['Er hat es doch aufgeschrieben.', 'Wo ist der Deckel?', 'Nein – niemand hat sie seitdem angefasst.'],
    hints: ['Ein Auge, das man nicht zugemacht hat.', 'Was schrieb er um 23.55 – und hat seitdem jemand die Kamera berührt?', 'Das Notizbuch, die Kamera selbst, und Mr. Hobbes.'],
    effects: { flags: ['g_camera_known'] },
  },
  {
    id: 'd12', chapter: 3, trigger: ['c24', 'c14', 'c23', 's39'], support: ['c24', 'c14', 'c23', 's39'], need: 2,
    question: 'Was wusste Miss Averley?',
    template: 'Miss Averley wusste, dass ihr Bruder {0}.',
    slots: [{ options: ['bald sterben würde', 'ermordet werden sollte', 'das Haus verkaufen wollte'], correct: [0] }],
    result: 'Harriet wusste von seiner Krankheit. „Er kommt bald zu mir“ ist keine Drohung. Es ist eine Schwester, die ihren Bruder schon verloren hat, bevor er starb.',
    doubt: ['Das ist mir zu dunkel für sie.', 'Nein. Was wusste er selbst seit August?', 'Wer ist „L.“?'],
    hints: ['„L.“ ist nicht Lionel.', 'Was wusste der Herr seit August?', 'Das Notizbuch (Bath) und das Blatt unter dem Séancetisch.'],
  },
  {
    id: 'd13', chapter: 4, trigger: ['c17', 'c18'], support: ['c17', 'c18', 'e02', 'c28'], need: 2,
    question: 'Wer war nachts auf der Haupttreppe?',
    template: 'In der Nacht lief {0} mit einer Talgkerze über die Haupttreppe bis vor {1} Tür.',
    slots: [
      { options: ['ein Dienstbote', 'jemand von der Familie', 'ein Gast'], correct: [0] },
      { options: ['Miss Claras', 'Miss Averleys', 'des Captains', 'Mrs. Penroses'], correct: [0] },
    ],
    result: 'Ein Dienstbote – mit Talg, nicht Wachs – lief nachts die verbotene Haupttreppe hinauf und wartete lange vor Claras Tür.',
    doubt: ['Die Herrschaft brennt Wachs. Talg ist für unten.', 'Wo genau lagen die Tropfen oben?', 'Nein. Das Klopfen im Traum war an einer bestimmten Tür.'],
    hints: ['Kerzen verraten ihren Stand.', 'Talg oder Wachs? Und wo oben liegen die Tropfen dicht beieinander?', 'Die Stufen und die Galerie vor den Türen.'],
  },
  {
    id: 'd14', chapter: 4, contradiction: true, trigger: ['c26'], support: ['s04', 's05', 'c26', 's36'], need: 2,
    question: 'Wo war Clara in der Nacht?',
    template: 'Clara sagt, sie sei zu Bett gegangen, Mrs. Penrose sagt, sie habe geschlafen. Aber {0}.',
    slots: [{ options: ['Claras Taschentuch lag unter dem Sessel im Gästezimmer', 'Clara hat schwarze Finger', 'Mrs. Penrose trägt Ringe', 'die Séance war um elf vorbei'], correct: [0] }],
    result: 'Clara war nachts bei Mrs. Penrose. Deshalb hat niemand geöffnet, als es an ihrer Tür klopfte.',
    doubt: ['Das beweist nur, dass sie Fotografin ist.', 'Wer hat etwas in wessen Zimmer vergessen?', 'Nein. Yuumi hat mir doch etwas gebracht.'],
    hints: ['Menschen lassen Dinge liegen, wo sie nicht sein wollten.', 'Was hat Yuumi im Gästezimmer gefunden?', 'Das Taschentuch – und Dunnings Licht im Gästeflügel.'],
  },
  {
    id: 'd15', chapter: 4, trigger: ['c22', 'c14', 's22'], support: ['c22', 'c14', 's22'], need: 2,
    question: 'Woher kannte das Medium die Glocke im Wasser?',
    template: 'Die Botschaft der Séance stammte {0}.',
    slots: [{ options: ['vom Herrn selbst, aus Bath', 'von Miss Averley', 'aus dem Jenseits', 'aus dem Dienstbotenklatsch'], correct: [0] }],
    result: 'Er hat es ihr selbst erzählt, im August in Bath, ohne seinen Namen zu nennen. Bei der Séance hörte er seine eigenen Worte – und begriff, dass sie aus seinem Mund kamen.',
    doubt: ['Miss Averley kannte Lucindas Wunsch. Aber die Worte am Sterbebett hat sie nicht gehört, sagt sie. Die kannte nur er.', 'Nein. Wer war im August in Bath?', 'Ich glaube nicht an Geister. Ich glaube an Karten in Schreibtischen.'],
    hints: ['Wer war im August wo?', 'Die Karte in seinem Schreibtisch – und sein eigener Eintrag über Bath.', 'Schreibtisch, Notizbuch, und frag Mrs. Penrose mit der Karte in der Hand.'],
  },
  {
    id: 'd16', chapter: 4, trigger: ['c29'], support: ['c29', 'c28', 'd13'], need: 2,
    question: 'Wer ist das Mädchen auf der Platte?',
    template: 'Das Mädchen, das auf der Platte mit einer Kerze auf der Treppe sitzt, ist {0}.',
    slots: [{ options: ['Tilly', 'Clara', 'eine Erscheinung', 'Mrs. Penrose'], correct: [0] }],
    result: 'Es ist Tilly. Sie saß nachts auf der Haupttreppe, lange genug, dass die Platte sie festhielt.',
    doubt: ['Clara trägt Wachs, und Clara hätte keine Haube auf.', 'Ich will nicht an Gespenster glauben. Nicht jetzt.', 'Nein. Wessen Kerze war heruntergebrannt?'],
    hints: ['Eine Haube, eine Talgkerze, eine Stufe.', 'Wer im Haus hatte am Morgen eine fast verbrannte Kerze?', 'Tillys Kerzenstummel in der Küche.'],
    effects: { flags: ['g_girl_known'] },
  },
  {
    id: 'd17', chapter: 4, trigger: ['d02', 'c27'], support: ['d02', 'c27', 'c28'], need: 2,
    question: 'Wen hat die Glocke gerufen?',
    template: 'Die Glocke um halb drei rief {0}, und {1} blieb sitzen.',
    slots: [
      { options: ['Tilly', 'Mr. Hobbes', 'Mrs. Pryce'], correct: [0] },
      { options: ['Mrs. Pryce', 'Mr. Hobbes', 'Tilly'], correct: [0] },
    ],
    result: 'Mrs. Pryce war wach, hörte die Glocke und ließ Tilly gehen. Sie selbst blieb sitzen. Deshalb lügt sie.',
    doubt: ['Hobbes schläft wie ein Stein, das sagen alle.', 'Wer war um zwei Uhr wach und hat es aufgeschrieben?', 'Nein – wer hat sich danach schuldig benommen?'],
    hints: ['Wer war wach?', 'Ein Brief, der um zwei Uhr früh begonnen und nicht beendet wurde.', 'Mrs. Pryces Tisch – und Tillys Kerze.'],
  },
  {
    id: 'd18', chapter: 5, trigger: ['c30'], support: ['c25', 'c30', 's11', 'd10'], need: 2,
    question: 'Was wollte er in seiner letzten Nacht?',
    template: 'In seiner letzten Nacht wollte der Herr {0}.',
    slots: [{ options: ['Clara den Weg öffnen und Lionel freisprechen', 'Lionel enterben', 'Lucinda rufen', 'das Haus verkaufen'], correct: [0] }],
    result: 'Er wollte alles in Ordnung bringen, bevor er ging: Lionels Schulden waren bezahlt, Clara sollte die Sammlung verkaufen und studieren. Er hat es nur niemandem rechtzeitig gesagt.',
    doubt: ['Das hat der Captain befürchtet. Das heißt nicht, dass es stimmt.', 'Nein. Was stand in dem Angebot aus Bath?', 'Lies den Brief noch einmal.'],
    hints: ['Was sollte am Morgen unterschrieben werden?', 'Das Angebot der Institution, der Brief, die Quittung.', 'Alles, was auf seinem Schreibtisch lag.'],
    effects: { flags: ['g_will_known'] },
  },
];

export const DEDUCTION_BY_ID = Object.fromEntries(DEDUCTIONS.map((d) => [d.id, d]));
