import type { NpcId } from '../engine/types';

export type KStatus = 'W' | 'A' | 'GF' | 'N' | 'V' | 'L';

export const FACTS: Record<string, string> = {
  f01: 'Edmund war schwer herzkrank.',
  f02: 'Edmund war im August bei Mrs. Penrose in Bath.',
  f03: 'Edmund hat Lionels Schulden bezahlt.',
  f04: 'Edmund wollte Clara das Studium ermöglichen.',
  f05: 'Clara stritt um 1 Uhr mit Edmund.',
  f06: 'Clara war 1.55–2.38 bei Mrs. Penrose.',
  f07: 'Lionel stritt ab 2.10 mit Edmund und ging, als der Anfall begann.',
  f08: 'Edmund läutete um 2.28.',
  f09: 'Tilly kam, bekam den Brief, lief über die Haupttreppe, klopfte an Claras Tür.',
  f10: 'Tilly war bei Edmund, als er starb.',
  f11: 'Tilly hat den Brief.',
  f12: 'Lionel stand um 2.45–2.50 auf der Terrasse.',
  f13: 'Lionel fand den Toten und verbrannte die Papiere.',
  f14: 'Hobbes fand Edmund am Boden und setzte ihn in den Sessel.',
  f15: 'Mrs. Pryce hörte die Glocke und blieb sitzen.',
  f16: 'Mrs. Penrose sah das Mädchen und die blasse Frau auf der Treppe.',
  f17: 'Die Kamera belichtete die ganze Nacht.',
  f18: 'Harriet schlief unter Chloral.',
  f19: 'Der Bittermandelgeruch stammt vom Fixierbad.',
  f20: 'Die Séance-Botschaft stammte aus Edmunds eigenem Mund.',
  f21: 'In der Nacht kam kein Boot.',
  f22: 'Die echte Miss Hale ist krank in Bristol.',
  f23: 'Sera kommt nicht aus dieser Zeit.',
  f24: 'Edmund wollte am Morgen etwas bezeugen lassen.',
  f25: 'Harriet lud Penrose wegen der Karte ein.',
  f26: 'Edmunds letzte Worte.',
  f27: 'Edmund sagte zu Lionel: „Die Glocke.“',
};

const row = (s: string): KStatus[] => s.split(' ') as KStatus[];
// Spalten: harriet lionel clara penrose hobbes pryce tilly dunning
const COLS: NpcId[] = ['harriet', 'lionel', 'clara', 'penrose', 'hobbes', 'pryce', 'tilly', 'dunning'];
const TABLE: Record<string, string> = {
  f01: 'V GF A A A A N N',
  f02: 'A GF V V N N N N',
  f03: 'N GF N N GF N N N',
  f04: 'A GF GF N A A N N',
  f05: 'N N V V N N N N',
  f06: 'N N L L N N N A',
  f07: 'N L N N A N N N',
  f08: 'N N N N N L V N',
  f09: 'N N N A N A L N',
  f10: 'N N N N N N V N',
  f11: 'N N N N N N V N',
  f12: 'N L N A N N A W',
  f13: 'N V N A A N N N',
  f14: 'GF V GF N L A N N',
  f15: 'N N N N N V A N',
  f16: 'N N N V N N N N',
  f17: 'GF N A N W N N N',
  f18: 'W A A A A W A N',
  f19: 'N GF W N A N N N',
  f20: 'GF GF V V N N N N',
  f21: 'GF N N N N A A W',
  f22: 'N N N N N N N N',
  f23: 'N N N A N N A N',
  f24: 'W W W W W W N N',
  f25: 'V N N A N N N N',
  f26: 'N N N N N N V N',
  f27: 'N V N N N N N N',
};

export const MATRIX: Record<NpcId, Record<string, KStatus>> = Object.fromEntries(
  COLS.map((npc, i) => [npc, Object.fromEntries(Object.entries(TABLE).map(([f, r]) => [f, row(r)[i]]))]),
) as Record<NpcId, Record<string, KStatus>>;

/** Lernereignisse: Nach Flag kennt die Figur die Tatsache (W). */
export const LEARN: { flag: string; npc: NpcId; fact: string }[] = [
  { flag: 'g_body_laid', npc: 'clara', fact: 'f14' },
  { flag: 'g_fix_shown', npc: 'lionel', fact: 'f19' },
  { flag: 'g_agency', npc: 'harriet', fact: 'f22' },
  { flag: 'g_agency', npc: 'hobbes', fact: 'f22' },
  { flag: 'g_agency', npc: 'pryce', fact: 'f22' },
  { flag: 'g_agency', npc: 'penrose', fact: 'f22' },
  { flag: 'g_agency', npc: 'clara', fact: 'f22' },
  { flag: 'g_agency', npc: 'lionel', fact: 'f22' },
  { flag: 'g_agency', npc: 'tilly', fact: 'f22' },
  { flag: 'g_plate_dev', npc: 'clara', fact: 'f17' },
  { flag: 'g_letter_read', npc: 'clara', fact: 'f01' },
  { flag: 'g_letter_read', npc: 'clara', fact: 'f03' },
  { flag: 'g_letter_read', npc: 'clara', fact: 'f04' },
  { flag: 'g_letter_read', npc: 'clara', fact: 'f09' },
  { flag: 'g_letter_read', npc: 'clara', fact: 'f10' },
  { flag: 'g_tilly_to_clara', npc: 'clara', fact: 'f26' },
  { flag: 'g_lionel_told_paid', npc: 'lionel', fact: 'f03' },
  { flag: 'g_lionel_told_words', npc: 'lionel', fact: 'f26' },
  { flag: 'g_harriet_confessed', npc: 'clara', fact: 'f01' },
  { flag: 'g_penrose_confessed', npc: 'clara', fact: 'f02' },
  { flag: 'g_penrose_confessed', npc: 'clara', fact: 'f20' },
  { flag: 'g_penrose_confessed', npc: 'harriet', fact: 'f20' },
  { flag: 'g_penrose_confessed', npc: 'harriet', fact: 'f02' },
  { flag: 'g_hobbes_confessed', npc: 'harriet', fact: 'f14' },
  { flag: 'g_pryce_confessed', npc: 'tilly', fact: 'f15' },
  { flag: 'g_tilly_spoke', npc: 'pryce', fact: 'f09' },
  { flag: 'g_tilly_spoke', npc: 'pryce', fact: 'f10' },
  { flag: 'g_lionel_confessed', npc: 'clara', fact: 'f07' },
  { flag: 'g_lionel_confessed', npc: 'harriet', fact: 'f07' },
  { flag: 'g_lionel_confessed', npc: 'clara', fact: 'f13' },
  { flag: 'g_sera_told_tilly', npc: 'tilly', fact: 'f23' },
  { flag: 'g_sera_told_penrose', npc: 'penrose', fact: 'f23' },
];
