import type { Statement } from '../engine/types';

// Aussagen fürs Notizbuch. truth ist nur intern (Tests/Doku), nie sichtbar.
export const STATEMENTS: Statement[] = [
  { id: 's01', speaker: 'hobbes', truth: 'luege', text: 'Ich fand den Herrn um Viertel nach sechs in seinem Sessel. Er war friedlich entschlafen.' },
  { id: 's02', speaker: 'pryce', truth: 'luege', text: 'Heut Nacht hat keine Glocke geläutet.' },
  { id: 's03', speaker: 'lionel', truth: 'luege', text: 'Ich war ab Mitternacht im Bett und habe geschlafen wie ein Stein.' },
  { id: 's04', speaker: 'clara', truth: 'luege', text: 'Ich bin nach der Séance zu Bett gegangen.' },
  { id: 's05', speaker: 'penrose', truth: 'luege', text: 'Ich schlafe in fremden Häusern ausgezeichnet. Ich habe nichts gehört.' },
  { id: 's06', speaker: 'dunning', truth: 'wahr', text: 'In der Nacht, kurz nach Viertel vor drei, stand der Captain hinten auf der Terrasse, mit dem Rücken zum Haus. Ohne Rock, im Regen.' },
  { id: 's07', speaker: 'tilly', truth: 'wahr', text: 'Heut Nacht hat was geklingelt auf der Treppe. So ganz fein.' },
  { id: 's08', speaker: 'tilly', truth: 'luege', text: 'Ich hab die ganze Nacht geschlafen. Wie ’n Sack Rüben.' },
  { id: 's09', speaker: 'penrose', truth: 'wahr', text: 'Wir sind uns schon begegnet. Heute Nacht.' },
  { id: 's10', speaker: 'hobbes', truth: 'wahr', text: 'Der Herr sagte um halb zwölf: „Lass es stehen, Hobbes. Bis zum Morgen. Niemand rührt es an.“' },
  { id: 's11', speaker: 'harriet', truth: 'wahr', text: 'Beim Dinner sagte Edmund, er brauche am Morgen Hobbes und Mrs. Pryce für eine Unterschrift.' },
  { id: 's12', speaker: 'lionel', truth: 'irrtum', text: 'Riechen Sie das? Bittermandel. Diese Frau hat ihn vergiftet.' },
  { id: 's13', speaker: 'clara', truth: 'wahr', text: 'Das ist kein Mord, das ist Fixierbad. Kaliumcyanid. Der Geruch zieht durch jede Tür.' },
  { id: 's14', speaker: 'dunning', truth: 'wahr', text: 'In der Nacht kam kein Boot übers Moor. Da wär keiner gefahren, nicht für Geld.' },
  { id: 's15', speaker: 'tilly', truth: 'wahr', text: 'Mr. Hobbes spült nie vor dem Frühstück. Aber Mittwoch früh, noch vor sieben, stand er in der Kammer und hat Gläser gespült.' },
  { id: 's16', speaker: 'harriet', truth: 'wahr', text: 'Ich habe geschlafen. Mrs. Pryce hat mir meine Tropfen gegeben.' },
  { id: 's17', speaker: 'pryce', truth: 'wahr', text: 'Mr. Hobbes hat sich heut früh was verrenkt. Er sagt, es ist das Wetter.' },
  { id: 's18', speaker: 'clara', truth: 'wahr', text: 'Wäre er im Sessel gestorben, wären die Totenflecken in Beinen und Becken. Sie sind an der linken Seite. Er hat Stunden am Boden gelegen.' },
  { id: 's19', speaker: 'penrose', truth: 'wahr', text: 'Der Captain riecht nach Rauch und hat frisch geschrubbte Hände. Man schrubbt sich nicht die Hände, wenn man nur geraucht hat.' },
  { id: 's20', speaker: 'lionel', truth: 'wahr', text: 'In der Nacht habe ich auf der Treppe ein Glöckchen gehört. Hinter dem Vorhang.' },
  { id: 's21', speaker: 'harriet', truth: 'wahr', text: 'Edmund hatte ein schwaches Herz. Wie unser Vater.' },
  { id: 's22', speaker: 'penrose', truth: 'wahr', text: 'Er kam im August zu mir nach Bath. Ohne Namen. Er erzählte mir von der Glocke im Wasser und von einem Versprechen.' },
  { id: 's23', speaker: 'clara', truth: 'wahr', text: 'Ich war nachts bei Mrs. Penrose. Von kurz vor zwei bis gegen zwanzig vor drei.' },
  { id: 's24', speaker: 'lionel', truth: 'wahr', text: 'Ich war auf der Terrasse. Ich brauchte Luft.' },
  { id: 's25', speaker: 'hobbes', truth: 'wahr', text: 'Ich fand ihn am Boden vor dem Kamin. Ich habe ihn in den Sessel gesetzt, und ich habe die Gläser fortgeräumt.' },
  { id: 's26', speaker: 'pryce', truth: 'wahr', text: 'Um halb drei hat die Glocke vom Arbeitszimmer geläutet. Das Kind ist gegangen. Ich bin sitzen geblieben.' },
  { id: 's27', speaker: 'tilly', truth: 'wahr', text: 'Der Herr hat mir einen Brief gegeben für Miss Clara. Ich hab an ihrer Tür geklopft, keiner hat aufgemacht. Wie ich zurückkam, lag er am Boden. Ich hab seine Hand gehalten.' },
  { id: 's28', speaker: 'tilly', truth: 'wahr', text: 'Er hat zuletzt gesagt: „Es ist bezahlt. Sag’s ihm.“' },
  { id: 's29', speaker: 'harriet', truth: 'wahr', text: 'Er wusste seit August, dass er sterben würde. Er hat mich schwören lassen, es den Kindern nicht zu sagen.' },
  { id: 's30', speaker: 'penrose', truth: 'wahr', text: 'Kurz vor drei sah ich von der Galerie ein weinendes Dienstmädchen auf der Treppe. Und neben ihr eine blasse Frau mit hellem Haar und einem kleinen Tier.' },
  { id: 's31', speaker: 'lionel', truth: 'wahr', text: 'Ich war bei ihm. Wir haben gestritten. Er griff sich an die Brust, und ich bin gegangen.' },
  { id: 's32', speaker: 'lionel', truth: 'wahr', text: 'Als ich zurückkam, lag er da. Auf dem Tisch lagen meine Schuldscheine. Ich habe sie verbrannt.' },
  { id: 's33', speaker: 'clara', truth: 'wahr', text: 'Um eins war ich bei ihm in der Dunkelkammer. Wir haben gestritten. Ich habe gesagt, Mama hätte sich für ihn geschämt.' },
  { id: 's34', speaker: 'pryce', truth: 'wahr', text: 'Sie haben saubere Hände und trockene Stiefel für eine, die übers Wasser gekommen ist.' },
  { id: 's35', speaker: 'tilly', truth: 'wahr', text: 'Die Stiefel vom Captain waren heut früh nass bis oben. Mit Erde vom Rosenbeet.' },
  { id: 's36', speaker: 'dunning', truth: 'wahr', text: 'Um halb drei war Licht im Gästeflügel. Hinter dem Fenster von der Dame aus Bath.' },
  { id: 's37', speaker: 'dunning', truth: 'wahr', text: 'Ich war ab zwei im Stall. Raus auf den Hof bin ich, wie die Stalluhr Viertel vor drei geschlagen hat.' },
  { id: 's39', speaker: 'harriet', truth: 'wahr', text: '(Hinter ihrer Tür) „Ich habe es niemandem gesagt, Edmund. Wie du es wolltest. Nicht Lionel. Nicht dem Kind.“' },
  { id: 's40', speaker: 'lionel', truth: 'wahr', text: 'Ich war nachts bei ihm. Wir haben gestritten, um Geld. Wie immer. Als ich ging, lebte er.' },
  { id: 's38', speaker: 'harriet', truth: 'wahr', text: 'Ich fand die Karte dieser Frau in Edmunds Schreibtisch. Ich dachte, er suche Lucinda.' },
];

export const STATEMENT_BY_ID = Object.fromEntries(STATEMENTS.map((s) => [s.id, s]));
